name: Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  sayOk:
    needs: lint
    runs-on: ubuntu-latest
      steps:
        - name: all ok
          run : echo "all ok"